
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceSumarImplService", targetNamespace = "http://beans/", wsdlLocation = "http://localhost:8080/ServiceSumarImplService/ServiceSumarImpl?wsdl")
public class ServiceSumarImplService
    extends Service
{

    private final static URL SERVICESUMARIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESUMARIMPLSERVICE_EXCEPTION;
    private final static QName SERVICESUMARIMPLSERVICE_QNAME = new QName("http://beans/", "ServiceSumarImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServiceSumarImplService/ServiceSumarImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESUMARIMPLSERVICE_WSDL_LOCATION = url;
        SERVICESUMARIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceSumarImplService() {
        super(__getWsdlLocation(), SERVICESUMARIMPLSERVICE_QNAME);
    }

    public ServiceSumarImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESUMARIMPLSERVICE_QNAME, features);
    }

    public ServiceSumarImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESUMARIMPLSERVICE_QNAME);
    }

    public ServiceSumarImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESUMARIMPLSERVICE_QNAME, features);
    }

    public ServiceSumarImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceSumarImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceSumarWS
     */
    @WebEndpoint(name = "ServiceSumarImplPort")
    public ServiceSumarWS getServiceSumarImplPort() {
        return super.getPort(new QName("http://beans/", "ServiceSumarImplPort"), ServiceSumarWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSumarWS
     */
    @WebEndpoint(name = "ServiceSumarImplPort")
    public ServiceSumarWS getServiceSumarImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans/", "ServiceSumarImplPort"), ServiceSumarWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESUMARIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICESUMARIMPLSERVICE_EXCEPTION;
        }
        return SERVICESUMARIMPLSERVICE_WSDL_LOCATION;
    }

}
